import PieceType from '../../models/piece_type';
import { PieceTypeNames } from '../../enums/piece_type_names';
import { grass, dirt } from './background';
import { bush } from './bush';
import { stone } from './stone';
import { tree_nw, tree_sw, tree_ne, tree_se } from './tree';

let pieceTypes: { [typeName: string] : PieceType } = {};
[grass, dirt, bush, stone, tree_nw, tree_sw, tree_ne, tree_se]
.map((pieceType) => {
  pieceTypes[pieceType.name] = pieceType;
});
["row-1-col-1.png",
"row-2-col-1.png",
"row-5-col-1.png",
"row-7-col-1.png",
"row-8-col-1.png",
"row-9-col-1.png",
"row-10-col-1.png",
"row-1-col-2.png",
"row-2-col-2.png",
"row-5-col-2.png",
"row-6-col-2.png",
"row-7-col-2.png",
"row-8-col-2.png",
"row-9-col-2.png",
"row-10-col-2.png",
"row-1-col-3.png",
"row-2-col-3.png",
"row-3-col-3.png",
"row-4-col-3.png",
"row-5-col-3.png",
"row-6-col-3.png",
"row-7-col-3.png",
"row-8-col-3.png",
"row-9-col-3.png",
"row-10-col-3.png",
"row-1-col-4.png",
"row-2-col-4.png",
"row-3-col-4.png",
"row-4-col-4.png",
"row-5-col-4.png",
"row-6-col-4.png",
"row-7-col-4.png",
"row-8-col-4.png",
"row-9-col-4.png",
"row-10-col-4.png",
"row-1-col-5.png",
"row-2-col-5.png",
"row-3-col-5.png",
"row-4-col-5.png",
"row-5-col-5.png",
"row-6-col-5.png",
"row-7-col-5.png",
"row-8-col-5.png",
"row-9-col-5.png",
"row-10-col-5.png",
"row-1-col-6.png",
"row-2-col-6.png",
"row-3-col-6.png",
"row-4-col-6.png",
"row-5-col-6.png",
"row-6-col-6.png",
"row-7-col-6.png",
"row-8-col-6.png",
"row-9-col-6.png",
"row-10-col-6.png",
"row-1-col-7.png",
"row-2-col-7.png",
"row-3-col-7.png",
"row-4-col-7.png",
"row-5-col-7.png",
"row-6-col-7.png",
"row-7-col-7.png",
"row-8-col-7.png",
"row-9-col-7.png",
"row-10-col-7.png",
"row-1-col-8.png",
"row-2-col-8.png",
"row-3-col-8.png",
"row-4-col-8.png",
"row-5-col-8.png",
"row-6-col-8.png",
"row-7-col-8.png",
"row-8-col-8.png",
"row-9-col-8.png",
"row-10-col-8.png",
"row-1-col-9.png",
"row-2-col-9.png",
"row-3-col-9.png",
"row-4-col-9.png",
"row-5-col-9.png",
"row-6-col-9.png",
"row-7-col-9.png",
"row-8-col-9.png",
"row-9-col-9.png",
"row-10-col-9.png",
"row-1-col-10.png",
"row-2-col-10.png",
"row-3-col-10.png",
"row-4-col-10.png",
"row-5-col-10.png",
"row-6-col-10.png",
"row-7-col-10.png",
"row-8-col-10.png",
"row-9-col-10.png",
"row-10-col-10.png", ].map((fileName) => {
  pieceTypes[fileName] = new PieceType({
    name: fileName,
    collidable: false,
    breakable: false,
    durability: null,
    animated: false,
    animationSteps: null,
    spriteNames: [fileName]
  });
})

export { pieceTypes };
