export enum PieceTypeNames {
  PLAYER = 'Player',
  BUSH = 'Bush',
  TREE_NW = 'Tree (NW)',
  TREE_SW = 'Tree (SW)',
  TREE_NE = 'Tree (NE)',
  TREE_SE = 'Tree (SE)',
  STONE = 'Stone',
  BACKGROUND = 'Background',
  GRASS = 'Grass',
  DIRT_SM = 'Dirt (small)',
  DIRT_N = 'Dirt (north)',
  DIRT_NE = 'Dirt (north-east)',
  DIRT_E = 'Dirt (east)',
  DIRT_SE = 'Dirt (south-east)',
  DIRT_S = 'Dirt (south)',
  DIRT_SW = 'Dirt (south-west)',
  DIRT_W = 'Dirt (west)',
  DIRT_NW = 'Dirt (north-west)',
  DIRT_M = 'Dirt (middle)',
  DIRT_H = 'Dirt (horizontal)',
  DIRT_V = 'Dirt (vertical)',
  CIRCLE_GLYPH_NE = 'Circle glyph (NE)',
  CIRCLE_GLYPH_SE = 'Circle glyph (SE)',
  CIRCLE_GLYPH_SW = 'Circle glyph (SW)',
  CIRCLE_GLYPH_NW = 'Circle glyph (NW)',
}
